#!/bin/bash
echo
echo Please select one of the following options:
echo
echo 'a = Add a record'
echo 'd = Delete a record'
echo
        read choice

                case $choice in
a) /home/iafzal/ps/add-record;;
d) /home/iafzal/ps/del-record;;
*) echo Invalid choice - Bye.

                esac